apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaiwa
resources:
  - ../../base
images:
  - name: harbor.gnzaga.com/apps/kaiwa
    newTag: latest
  - name: harbor.gnzaga.com/apps/kaiwa-embedder
    newTag: latest
  - name: harbor.gnzaga.com/apps/kaiwa-researcher
    newTag: latest
  - name: harbor.gnzaga.com/apps/kaiwa-webreader
    newTag: latest
