apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaiwa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gnzaga/kaiwa.git
    targetRevision: master
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kaiwa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
