service:
  type: LoadBalancer

appSettings:
  disableWebUi: "false"
  metrics: "true"

appConfig:
  loadOnly: "en,ja,es,zh,tl,de,fr"
  frontendLanguageSource: "ja"
  frontendLanguageTarget: "en"

persistence:
  enabled: true
  models:
    storageClass: nfs-csi
    accessMode: "ReadWriteMany"
    size: "10Gi"

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "6Gi"

livenessProbe:
  exec:
    command:
    - /app/venv/bin/python
    - scripts/healthcheck.py
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  exec:
    command:
    - /app/venv/bin/python
    - /app/scripts/healthcheck.py
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 5
