apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kaiwa
  labels:
    app.kubernetes.io/name: kaiwa
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: https://auth.gnzaga.com/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: https://auth.gnzaga.com/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kaiwa.gnzaga.com
      secretName: kaiwa-tls
  rules:
    - host: kaiwa.gnzaga.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kaiwa-web
                port:
                  name: http
