apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-web.yaml
  - deployment-worker.yaml
  - deployment-embedder.yaml
  - deployment-researcher.yaml
  - service.yaml
  - service-embedder.yaml
  - service-researcher.yaml
  - ingress.yaml
  - ingress-auth-bypass.yaml
  - external-secret.yaml
  - externalsecret-harbor.yaml
  - scaledobject-embedder.yaml
