apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-web.yaml
  - deployment-worker.yaml
  - service.yaml
  - ingress.yaml
  - ingress-auth-bypass.yaml
  - external-secret.yaml
  - externalsecret-harbor.yaml
  - pvc-db.yaml
