apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kaiwa-embedder
  labels:
    app.kubernetes.io/name: kaiwa
    app.kubernetes.io/component: embedder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kaiwa-embedder
  minReplicaCount: 1
  maxReplicaCount: 6
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "75"
