apiVersion: v1
kind: Service
metadata:
  name: kaiwa-web
  labels:
    app.kubernetes.io/name: kaiwa
    app.kubernetes.io/component: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kaiwa
    app.kubernetes.io/component: web
