apiVersion: v1
kind: Service
metadata:
  name: kaiwa-embedder
  labels:
    app.kubernetes.io/name: kaiwa
    app.kubernetes.io/component: embedder
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kaiwa
    app.kubernetes.io/component: embedder
