apiVersion: v1
kind: Service
metadata:
  name: kaiwa-searxng
  labels:
    app.kubernetes.io/name: kaiwa
    app.kubernetes.io/component: searxng
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kaiwa
    app.kubernetes.io/component: searxng
